name: CD

on:
  push:
    paths:
      - 'VERSION'

jobs:
  release:
    uses: jeffersonlab/container-workflows/.github/workflows/gh-release.yaml@v2
    secrets: inherit

  docker_publish:
    needs:
      - release
    uses: jeffersonlab/container-workflows/.github/workflows/docker-publish.yaml@v2
    with:
      semvertag: ${{ needs.release.outputs.semvertag }}
    secrets: inherit
